### PR TITLE
[EXTERNAL] Fixing a few minor things in subjects from the RUST piscine

### PR DESCRIPTION
**Pull request by TheOldestBrother**
### Why?
A few student and myself found a few things that could be improved in different subjects README files, I did my best to attend to these changes.

1 - Adding a reminder of what a **prime number** is, a few student didn't remembered in an exam and were stuck because of that. 

2 - Specifying the input type awaited by the test program to avoid a simple mistake and some frustration.

3 - Modifying the example for the `nb_games` : a few people struggle with this as they didn't understand that this input would determine a few other variables. I thought that with 2 examples the point would be made clearer.

### CODE REVIEW

**Comment by pedrodesu** [comment]
Hello @TheOldestBrother!

First and foremost, do excuse us for the delay, I was just now assigned this case. We appreciate your suggestion!
I took a look at your proposition. It seems interesting, especially given that it takes into account direct feedback from students from schools.
I made some minor changes for matters of uniformity and so it's according to the master branch as is and our Prettier workflow. They'll be pushed as soon as possible. Please let me know what you think of them and do comment further on it if you have some additional feedback.

Thank you very much.

**Review by MSilva95 — APPROVED** [review]
LGTM!

**Comment by pedrodesu** [comment]
Hello @TheOldestBrother!

Your PR was written in very good means, you've nothing to worry in that regard!

About future suggestions, we of course welcome any feedback you or any peer of yours might want to share. We're continuously striving to improve our content so all suggestions are welcome, especially if it comes directly from our zones.
You should also know the content team is giving careful attention to the Rust piscine at the moment, so changes inside of it are to be expected briefly. Some of these changes do already take into account direct feedback from the zones' students, but nevertheless, please feel free to let us know where we can improve!

Regarding your last request, as I mentioned previously, you don't really have much to worry about, your PR was well formed and I didn't need to do too much extra work on it. What I can tell you regarding this repository is to kindly follow the convention that appears when you go for creating a PR, as it seems you properly did on this one.

We appreciate your time and your help a lot!

**Comment by TheOldestBrother** [comment]
Hello @pedrodesu,

I'm happy that I could be of some help and will come back in the future with more feedback! I thank you for your time, this has been very interesting learning point for me.

A good day to you!

**Pull request merged**
