### PR TITLE
Piscine-Scripting Quest 1 : Update README.md strange-files

### PR DESCRIPTION
**Pull request by lotoussa**
consistant file name in the subject and corresponding to the test

### CODE REVIEW

**Comment by lotoussa** [comment]
related issue : https://01talent.atlassian.net/browse/SUP-401

**Review by MSilva95 — APPROVED** [review]
the changes LGTM!

**Review by MSilva95 — CHANGES_REQUESTED** [review]
The checks are failing.

**Review by MSilva95 — APPROVED** [review]

**Comment by lotoussa** [comment]
Hi, why this fix isn't up to date on adn-training ?

**Comment by MSilva95** [comment]
image
it shows the updated version on my side where did you saw the old version?

**Comment by MSilva95** [comment]
On mine its good...
image
same link as yours... maybe if you do a hard reload of the page it will be good, if not try to clear you cache ...

**Comment by lotoussa** [comment]
lol
I've actually faked the image to illustrate the problem I'm having. This exercise is duplicated from the reference object, which does have the expected files problem.

**Comment by lotoussa** [comment]
this one actually work because i've modified the object attributes but this isn't the default attributes.
image

**Pull request merged**
