### PR TITLE
beginEnd case correction

### PR DESCRIPTION
**Pull request by azamatamirzhan**
'hired kimchi' has 'hi' in the beginnig and in the end

### CODE REVIEW

**Comment by OGordoo** [comment]
HI @azamatamirzhan, `beginEnd` should be true if the same instance of 'hi' is simultaneously in the beginning and in the end

**Comment by kigiri** [comment]
> HI @azamatamirzhan, `beginEnd.test(...)` should be true if the same instance of 'hi' is simultaneously in the beginning and in the end

maybe we can try to make this clearer in the subject @OGordoo ?

**Comment by azamatamirzhan** [comment]
'hired kimchi' has 'hi' in the end, and in the beginning too.
Written program must return true - am I right?

**Comment by OGordoo** [comment]
@kigiri Okay, I'm going to make it clearer on the subject

**Pull request closed without merging**
